name: centos7-glibc2.32
on:
  schedule:
    - cron: '30 23 5,15,30 * *'
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: '' # 如果为空，则使用 DockerHUb

jobs:
  build:
    # 运行环境 
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - name: "拉取仓库代码"
        uses: actions/checkout@v3
      - name: "登录 Docker Hub " 
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "构建镜像"
        run: |
          pwd && ls
          cd centos7-glibc2.32
          pwd && ls
          docker build -t ${{ secrets.DOCKER_USERNAME }}/centos7:glibc2.32 --no-cache --force-rm .
      - name: "推送镜像"
        run: |
          pwd && ls
          cd centos7-glibc2.32
          pwd && ls
          docker push ${{ secrets.DOCKER_USERNAME }}/centos7:glibc2.32    
            
     